config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/todos', to: 'todos#index'
  get '/todos/list', to: 'todos#list', as: 'todo_list'
  get 'todos/new', to: 'todos#new'
  post '/todos', to: 'todos#create'
  get '/todos/:id', to: 'todos#show', as: 'todo'
  get '/todos/:id/edit', to: 'todos#edit', as: 'todo_edit'
  patch '/todos/:id', to: 'todos#update'
  delete '/todos/:id', to: 'todos#destroy'
  get '/todos/:id/complete', to: 'todos#complete', as: 'todo_complete'
  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :todo_find, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @todos = Todo.all
  end

  def list
    todos = Todo.all
    @completed = todos.where(completed: true)
    @not_completed = todos.where(completed: false)
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    @todo.save
    redirect_to root_path
  end

  def show
    #@todo = Todo.find(params[:id])
  end

  def edit
    #@todo = Todo.find(params[:id])
  end

  def update
    #@todo = Todo.find(params[:id])
    @todo.update(todo_params)
    redirect_to root_path
  end

  def destroy
    #@todo = Todo.find(params[:id])
    @todo.destroy
    redirect_to root_path
  end

  def complete
    #@todo = Todo.find(params[:id])
    @todo.completed = true
    @todo.save
    redirect_to root_path
  end

  private
  def todo_params
    params.require(:todo).permit(:description, :completed)
  end

  def todo_find
    @todo = Todo.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mx-auto">
      <li class="nav-item">
        <a class="btn btn-outline-info mx-1 my-1" href="<%= root_path %>">Home</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-outline-info mx-1 my-1" href="<%= todo_list_path %>">List</a>
      </li>
      <li class="nav-item">
        <a class="btn btn-outline-success mx-1 my-1" href="<%= todos_new_path %>">Nuevo Registro</a>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prueba03</title>
    <%= csrf_meta_tags %>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with model: @todo, local: true do |f| %>
  <div class="form-group">
    <%= f.label :description, 'Descripción:' %>
    <%= f.text_area :description, class: 'form-control' %>

    <%= f.label :completed, 'Completado:' %>
    <%= f.check_box :completed, class: 'checkbox' %>
  </div>

  <%= f.submit 'Enviar', class: 'btn btn-info' %>
<% end %>

app/views/todos/edit.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-sm-12 col-md-6 col-lg-8">
    <h3 class="text-info">Editar registro:</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/todos/index.html.erb
<div class="row">
  <div class="col-12 my-3 table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">Tarea</th>
          <th scope="col">Estado</th>
          <th scope="col"></th>
        </tr>
      </thead>
      <tbody>
        <% @todos.each do |todo| %>
        <tr>
          <td><%= todo.description %></td>
          <% if todo.completed %>
            <td>Completado :)</td>
          <% else %>
            <td>Incompleto :(</td>
          <% end %>
          <td>
          <div class="d-flex justify-content-start">
            <%= link_to 'Mostrar', todo_path(todo.id), class: 'btn btn-info btn-sm mx-1' %>
            <%= link_to 'Editar', todo_edit_path(todo.id), class: 'btn btn-warning btn-sm mx-1' %>
            <%= link_to 'Eliminar', todo_path(todo.id), method: :delete, class: 'btn btn-danger btn-sm mx-1' %>
            <% if !todo.completed %>
              <%= link_to 'Completar', todo_complete_path(todo.id), class: 'btn btn-success btn-sm mx-1' %>
            <% end %>
          </div>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>


<%= link_to 'Nuevo', todos_new_path, class: 'btn btn-outline-primary' %>

app/views/todos/list.html.erb
<h3 class="text-info">Listado:</h3>
<div class="row">
  <div class="col-sm-12 col-md-6 col-lg-6">
    <ul class="list-group">
      <li class="list-group-item list-group-item-danger"><h4>No completados:</h4></li>
      <% @not_completed.each do |todo| %>
        <li class="list-group-item"><%= todo.description %></li>
      <% end %>
    </ul>  
  </div>

  <div class="col-sm-12 col-md-6 col-lg-6">
    <ul class="list-group">
      <li class="list-group-item list-group-item-success"><h4>Completados:</h4></li>
      <% @completed.each do |todo| %>
        <li class="list-group-item"><%= todo.description %></li>
      <% end %>
    </ul>  
  </div>
</div>

app/views/todos/new.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-sm-12 col-md-6 col-lg-8">
    <h3 class="text-info">Nuevo registro:</h3>
    <%= render 'form' %>
  </div>
</div>

app/views/todos/show.html.erb
<div class="row d-flex justify-content-center">
  <div class="col-md-7">
    <h5> Description: <%= @todo.description %></h5>
    <h5> Completado: <b><%= @todo.completed %></b> </h5>
    <p> Creado hace: <%= time_ago_in_words @todo.created_at %> </p>
    <%= link_to "Volver", todos_path, class: 'btn btn-primary' %>
  </div>
</div>